// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEBtXlLhPGZtQV0n-Wv7O87vkE1Yit6Bc',
    appId: '1:65439853703:web:669be5e54eb0cbc9f85c22',
    messagingSenderId: '65439853703',
    projectId: 'sos-app-a03fb',
    authDomain: 'sos-app-a03fb.firebaseapp.com',
    storageBucket: 'sos-app-a03fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGk4IuYNfxUqFSGgnOyebMCzQUUzsxw4',
    appId: '1:65439853703:android:39592d9346643a3ef85c22',
    messagingSenderId: '65439853703',
    projectId: 'sos-app-a03fb',
    storageBucket: 'sos-app-a03fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpe4DfmurHYiJgVH9cOxFfUVLwN7sBcs',
    appId: '1:65439853703:ios:d2513a423dd9d89af85c22',
    messagingSenderId: '65439853703',
    projectId: 'sos-app-a03fb',
    storageBucket: 'sos-app-a03fb.firebasestorage.app',
    iosBundleId: 'com.example.sos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMpe4DfmurHYiJgVH9cOxFfUVLwN7sBcs',
    appId: '1:65439853703:ios:d2513a423dd9d89af85c22',
    messagingSenderId: '65439853703',
    projectId: 'sos-app-a03fb',
    storageBucket: 'sos-app-a03fb.firebasestorage.app',
    iosBundleId: 'com.example.sos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEBtXlLhPGZtQV0n-Wv7O87vkE1Yit6Bc',
    appId: '1:65439853703:web:522c8db634765d94f85c22',
    messagingSenderId: '65439853703',
    projectId: 'sos-app-a03fb',
    authDomain: 'sos-app-a03fb.firebaseapp.com',
    storageBucket: 'sos-app-a03fb.firebasestorage.app',
  );
}
